		PrimeFaces.locales['cs'] = {
			closeText : 'Zavřít',
			prevText : 'Předchozí',
			nextText : 'Následující',
			monthNames : [ 'Leden', 'Únor', 'Březen', 'Duben', 'Květen', 'Červen', 'Červenec', 'Srpen', 'Září', 'Říjen', 'Listopad', 'Prosinec' ],
			monthNamesShort : [ 'Led', 'Úno', 'Bře', 'Dub', 'Kvě', 'Čer', 'Čvc', 'Srp', 'Zář', 'Říj', 'Lis', 'Pro' ],
			dayNames : [ 'Neděle', 'Pondělí', 'Úterý', 'Středa', 'Čtvrtek', 'Pátek', 'Sobota' ],
			dayNamesShort : [ 'Ne', 'Po', 'Út', 'St', 'Čt', 'Pá', 'So' ],
			dayNamesMin : [ 'Ne', 'Po', 'Út', 'St', 'Čt', 'Pá', 'So' ],
			weekHeader : 'Týden',
			firstDay : 1,
			isRTL : false,
			showMonthAfterYear : false,
			yearSuffix : '',
			timeOnlyTitle : 'Pouze čas',
			timeText : 'Čas',
			hourText : 'Hodina',
			minuteText : 'Minuta',
			secondText : 'Sekunda',
			currentText : 'Nyní',
			ampm : false,
			month : 'Měsíc',
			week : 'Týden',
			day : 'Den',
			allDayText : 'Celý den'
		};

		PrimeFaces.locales['it'] = {
			closeText : 'Chiudi',
			prevText : 'Precedente',
			nextText : 'Prossimo',
			monthNames : [ 'Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre',
					'Dicembre' ],
			monthNamesShort : [ 'Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic' ],
			dayNames : [ 'Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato' ],
			dayNamesShort : [ 'Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab' ],
			dayNamesMin : [ 'D', 'L', 'M', 'M ', 'G', 'V ', 'S' ],
			weekHeader : 'Sett',
			firstDay : 1,
			isRTL : false,
			showMonthAfterYear : false,
			yearSuffix : '',
			timeOnlyTitle : 'Solo Tempo',
			timeText : 'Ora',
			hourText : 'Ore',
			minuteText : 'Minuto',
			secondText : 'Secondo',
			currentText : 'Data Odierna',
			ampm : false,
			month : 'Mese',
			week : 'Settimana',
			day : 'Giorno',
			allDayText : 'Tutto il Giorno'
		};